### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by davidshepherd7** [python-smpplib/python-smpplib#107]
Hi, am I correct in thinking that this library doesn't currently support connecting over TLS?

If I was to implement support would it be something that you would be interested in merging?

**Comment by davidshepherd7** [comment]
I think I'll try to add something that works similarly to smtplib as shown here: https://docs.python.org/3/library/ssl.html#best-defaults

**Comment by podshumok** [comment]
Sure, go ahead! We aren't very active and we are kinda slow, but we do reviews and we merge PRs,
