### ISSUE TITLE
Unknown optional parameter codes are not being ignored

### ISSUE THREAD

**Issue by davidshepherd7** [python-smpplib/python-smpplib#111]
Hi,

the spec (https://smpp.org/SMPP_v3_4_Issue1_2.pdf page 43) says that when parsing a PDU if an unknown optional parameter is seen it should be ignored, but at the moment an error is thrown.

I'd like to change it to obey the spec. Do you think a patch doing that would be ok to merge?

This is a subset of issue #105 because I'm only interested in ignoring custom parameter codes (not parsing them).

**Comment by eigenein** [comment]
Hi David,

I think it's fine by me, let's follow the specs

**Comment by podshumok** [comment]
I would suggest to make it configurable as it would be a breaking change

**Comment by davidshepherd7** [comment]
> I would suggest to make it configurable as it would be a breaking change

Yeah that's what I was worried about. How about I make it configurable and you guys can flip the default (or remove the flag entirely) if/when you feel comfortable with making a breaking change?
