### ISSUE TITLE
Socket receive never times out, causing disconnection on inactivity.

### ISSUE THREAD

**Issue by telemix** [python-smpplib/python-smpplib#119]
In `client.py -> read_pdu` the socket.recv() never times out, so the enquire_link is never sent and the connection is terminated by the server due to inactivity (most commercial servers require a keep-alive every 60 seconds). Here's the offending code : 
```python
            try:
                raw_len = self._socket.recv(4)
            except socket.timeout:
                raise
            except socket.error as e:
                self.logger.warning(e)
                raise exceptions.ConnectionError()
            if not raw_len:
                raise exceptions.ConnectionError()
```

Changing it to this appears to solve it : 
```python
        ready = select.select([self._socket], [], [], 55)
        if ready[0]:
            try:
                raw_len = self._socket.recv(4)
            except socket.timeout:
                raise
            except socket.error as e:
                self.logger.warning(e)
                raise exceptions.ConnectionError()
            if not raw_len:
                raise exceptions.ConnectionError()
        else:
            raise socket.timeout
```

Is that an acceptable fix? If so, should I create a pull request (I've never done one before)?

**Comment by davidshepherd7** [comment]
Is your version of smpplib fully up to date? This PR should address this issue: https://github.com/python-smpplib/python-smpplib/pull/122

`recv` has a timeout already, but it's configured when you create the socket. Previously it wasn't being configured correctly in some cases.
