### ISSUE TITLE
while using bind_transmitter getting KeyError 22

### ISSUE THREAD

**Issue by febinpaul** [python-smpplib/python-smpplib#12]
while using bind_transmitter I am getting KeyError 22
ie  SMPP_ESME_RINVSUBREP: 'Invalid Submit With Replace request (replace_if_present_flag set)',

Please give me some suggestion....

**Comment by podshumok** [comment]
Could you please post some code, traceback and debug-level logs?

**Comment by febinpaul** [comment]
Thank you for considering my request.

#Client configuration:

client = smpplib.client.Client('ip', port) # south
client.connect()
client.bind_transmitter(system_id='system_id', password='password') #south

parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts('hello')
for part in parts:
	pdu = client.send_message(
	    source_addr_ton=smpplib.consts.SMPP_TON_INTL,
	    # source_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
	    source_addr='source_addr',
	    dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
	    # dest_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
	    destination_addr='919496608602',
	    short_message=part,
	    data_coding=encoding_flag,
	    esm_class=msg_type_flag
	)

While running, using the bind_transmitter() function, I getting this error:

INFO:smpplib.client:Connecting to IP:PORT...
DEBUG:smpplib.client:Receiver mode
DEBUG:smpplib.client:Sending bind_transmitter PDU
DEBUG:smpplib.client:>>000000250000000200000000000000016d75626c6554006d75626c65313233000034000000 (37 bytes)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<000000178000000200000016000000016d75626c655400 (23 bytes)
DEBUG:smpplib.client:Reads bind_transmitter_resp PDU
Traceback (most recent call last):
  File "example.py", line 34, in <module>
    client.bind_transmitter(system_id='system_id', password='password') #south
  File "/home/dev1/workshop/python/test/python-smpplib-master/smpplib/client.py", line 154, in bind_transmitter
    return self._bind('bind_transmitter', **kwargs)
  File "/home/dev1/workshop/python/test/python-smpplib-master/smpplib/client.py", line 149, in _bind
    consts.DESCRIPTIONS[resp.status]), int(resp.status))
KeyError: 22
WARNING:smpplib.client:Command unbind failed: Incorrect BIND Status for given command. Ignored
INFO:smpplib.client:Disconnecting...


Please convey if you need any other information

**Comment by podshumok** [comment]
Looks like the server is using one of reserved error codes. The library is not aware of this code (0x16, 22 in decimal). You should consult with server admin/SMPP provider.
