### ISSUE TITLE
sms cycle

### ISSUE THREAD

**Issue by maoneid** [python-smpplib/python-smpplib#126]
how to send multiple or asynchronous process?

**Comment by eigenein** [comment]
Hi, what do you mean exactly?

**Comment by maoneid** [comment]
in example, the process is for sendmessage, then call listen method for listen. is it possible to send multiple messages?

**Comment by eigenein** [comment]
Sure, what's your issue exactly? What have you already tried?

**Comment by eigenein** [comment]
Please, reopen if this is still a question.
