### ISSUE TITLE
Condition to split the text in `make_parts` function

### ISSUE THREAD

**Issue by fpalamour** [python-smpplib/python-smpplib#182]
I noticed that when my message is 160 characters but it contains the char € (or any symbols from extended table), the encoded_length is 161 as it should be, since the € char counts for two. However, in the make_parts function from gsm.py, the condition for knowing if the message should be split or not is based on `len(text)` which returns 160. To me, the condition should be based on `len(encoded_text)`

Edit : I noticed it because of submit_sm_resp failed and the ESME told me I wasn't splitting the message although it was 161 characters.

**Comment by fpalamour** [comment]
Hi  @eigenein,

I tested the proposed fix the day I created the issue, and my problem has been gone ever since. Also, the PR has also just been created.

**Comment by eigenein** [comment]
Hi @fpalamour,

Thanks for the fix! It's merged and published under `2.2.1`.

**Comment by fpalamour** [comment]
Anytime !
