### ISSUE TITLE
Refactor socket read/write

### ISSUE THREAD

**Issue by emnoor** [python-smpplib/python-smpplib#196]
I have a few propositions regarding socket usage in `send_pdu()` and `read_pdu()` methods.

1.
Here, instead of manually tracking how much is sent in a loop, using `socket.sendall()` method should make the code more concise and readable. https://github.com/python-smpplib/python-smpplib/blob/9ca29cfa88bb9fa159b6dc52839ffd5482f8ac0e/smpplib/client.py#L215-L225

2.
In `read_pdu`, we don't check `len(raw_len) == 4`. For less than 4 bytes we raise `PDUError`. But we could possibly get `raw_len` in multiple with `recv`, just like when we are reading the rest of the PDU.

I propose we refactor the "keep `recv`ing until we got all bytes" into a separate method (i.e. `_recv_exact(n)`), and then read `raw_len` and `raw_pdu` with this method.

If you are interested, I will send pull requests for these changes.

**Comment by eigenein** [comment]
Hi @emnoor,

Thanks for the suggestions! We've got quite a legacy code of 7-8 years old, hence the quirks. Yeah, pull requests for these are very welcome!

**Comment by emnoor** [comment]
https://github.com/python-smpplib/python-smpplib/pull/197 and https://github.com/python-smpplib/python-smpplib/pull/198
