### ISSUE TITLE
Sequence number is not incremented according to spec for some commands

### ISSUE THREAD

**Issue by emnoor** [python-smpplib/python-smpplib#214]
Sequence incrementing is disabled for the following commands, but the SMPP v3.4 spec requires them to have a unique sequence number:

- `BindTransmitter` ([ref](https://smpp.org/SMPP_v3_4_Issue1_2.pdf#page=46))
- `BindReceiver` ([ref](https://smpp.org/SMPP_v3_4_Issue1_2.pdf#page=48))
- `BindTransceiver` ([ref](https://smpp.org/SMPP_v3_4_Issue1_2.pdf#page=51))
- `DeliverSM` ([ref](https://smpp.org/SMPP_v3_4_Issue1_2.pdf#page=79))
- `Unbind` ([ref](https://smpp.org/SMPP_v3_4_Issue1_2.pdf#page=56))
- `EnquireLink` ([ref](https://smpp.org/SMPP_v3_4_Issue1_2.pdf#page=106))

Currently I am facing an issue with an SMSC for this.

If you are interested, I will send pull requests for these changes.

**Comment by eigenein** [comment]
Thank you, I've just published `2.2.2` with the fix included
