### ISSUE TITLE
Wrong split length

### ISSUE THREAD

**Issue by wciurzynski** [python-smpplib/python-smpplib#216]
After PR #184 UCS2_LENGTH should be changed from 70 to 140.
Message which is encoded in UCS-2 has a maximum of 70 characters but after encoding to utf-16-be len of encoded text is twice as large.

**Comment by eigenein** [comment]
Hi @wciurzynski,

Thanks for reporting it, it actually makes sense to me. Did you verify that it actually works correctly?

**Comment by wciurzynski** [comment]
Yes, I did :)

**Comment by eigenein** [comment]
Thanks @wciurzynski, this is fixed in `2.2.3`.
