### ISSUE TITLE
Sending bind_transceiver PDU

### ISSUE THREAD

**Issue by sairmali** [python-smpplib/python-smpplib#223]
EBUG:smpp.Client.2560105653648:Sending bind_transceiver PDU
DEBUG:smpp.Client.2560105653648:>>b'00000029000000090000000000000002446172416c6b65657261004440724132303233000034000000' (41 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'0000001b800000090000000000000002446172416c6b6565726100' (27 bytes)
DEBUG:smpp.Client.2560105653648:Read bind_transceiver_resp PDU
DEBUG:smpp.Client.2560105653648:Sending submit_sm PDU
DEBUG:smpp.Client.2560105653648:>>b'000000c700000004000000000000000300050053454e44455250484f4e454e554d000101393632373838333831383031004000000000010008008c050003600201041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020' (199 bytes)
3
DEBUG:smpp.Client.2560105653648:Sending submit_sm PDU
DEBUG:smpp.Client.2560105653648:>>b'000000ab00000004000000000000000400050053454e44455250484f4e454e554d0001013936323738383338313830310040000000000100080070050003600202043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a' (171 bytes)
4
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000019800000040000000000000003303742393346354600' (25 bytes)
DEBUG:smpp.Client.2560105653648:Read submit_sm_resp PDU
sent 3 b'07B93F5F'
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000019800000040000000000000004303742393346363000' (25 bytes)
DEBUG:smpp.Client.2560105653648:Read submit_sm_resp PDU
sent 4 b'07B93F60'
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:Socket timeout, listening again
DEBUG:smpp.Client.2560105653648:Sending enquire_link PDU
DEBUG:smpp.Client.2560105653648:>>b'00000010000000150000000000000005' (16 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000010800000150000000000000005' (16 bytes)
DEBUG:smpp.Client.2560105653648:Read enquire_link_resp PDU
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:Socket timeout, listening again
DEBUG:smpp.Client.2560105653648:Sending enquire_link PDU
DEBUG:smpp.Client.2560105653648:>>b'00000010000000150000000000000006' (16 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000010800000150000000000000006' (16 bytes)
DEBUG:smpp.Client.2560105653648:Read enquire_link_resp PDU
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:Socket timeout, listening again
DEBUG:smpp.Client.2560105653648:Sending enquire_link PDU
DEBUG:smpp.Client.2560105653648:>>b'00000010000000150000000000000007' (16 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000010800000150000000000000007' (16 bytes)
DEBUG:smpp.Client.2560105653648:Read enquire_link_resp PDU
DEBUG:smpp.Client.2560105653648:Waiting for PDU...

**Comment by sairmali** [comment]
import logging
import sys

import smpplib.gsm
import smpplib.client
import smpplib.consts

# if you want to know what's happening
logging.basicConfig(level='DEBUG')

# Two parts, UCS2, SMS with UDH
parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(u'Привет мир!\n'*10)

client = smpplib.client.Client('my ip', 2775, allow_unknown_opt_params=True)

# Print when obtain message_id
client.set_message_sent_handler(
    lambda pdu: sys.stdout.write('sent {} {}\n'.format(pdu.sequence, pdu.message_id)))
client.set_message_received_handler(
    lambda pdu: sys.stdout.write('delivered {}\n'.format(pdu.receipted_message_id)))

client.connect()
client.bind_transceiver(system_id='<username>', password='<password>')

for part in parts:
    pdu = client.send_message(
        source_addr_ton=5,
        source_addr_npi=0,
        # Make sure it is a byte string, not unicode:
        source_addr='SENDERPHONENUM',

        dest_addr_ton=1,
        dest_addr_npi=1,
        # Make sure thease two params are byte strings, not unicode:
        destination_addr='<phone number>',
        short_message=part,

        data_coding=encoding_flag,
        esm_class=msg_type_flag,
        registered_delivery=True,
        auto_send_enquire_link=False
    )
    print(pdu.sequence)
    
# Enters a loop, waiting for incoming PDUs
client.listen()

**Comment by eigenein** [comment]
👋 @sairmali What kind of update are you expecting?

**Comment by sairmali** [comment]
thanks for asking @eigenein. i am getting this error after use this

**Comment by eigenein** [comment]
I'm not sure I understand, which error?

**Comment by sairmali** [comment]
basically, i am using smpp server for sending message to phone number, but unfortunately i am not receive any incoming message from my smpp server and also i am using your library fot this 

please can you can check above i have wright a code from your github page and pass all parameters.



response:--
EBUG:smpp.Client.2560105653648:Sending bind_transceiver PDU
DEBUG:smpp.Client.2560105653648:>>b'00000029000000090000000000000002446172416c6b65657261004440724132303233000034000000' (41 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'0000001b800000090000000000000002446172416c6b6565726100' (27 bytes)
DEBUG:smpp.Client.2560105653648:Read bind_transceiver_resp PDU
DEBUG:smpp.Client.2560105653648:Sending submit_sm PDU
DEBUG:smpp.Client.2560105653648:>>b'000000c700000004000000000000000300050053454e44455250484f4e454e554d000101393632373838333831383031004000000000010008008c050003600201041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020' (199 bytes)
3
DEBUG:smpp.Client.2560105653648:Sending submit_sm PDU
DEBUG:smpp.Client.2560105653648:>>b'000000ab00000004000000000000000400050053454e44455250484f4e454e554d0001013936323738383338313830310040000000000100080070050003600202043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a' (171 bytes)
4
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000019800000040000000000000003303742393346354600' (25 bytes)
DEBUG:smpp.Client.2560105653648:Read submit_sm_resp PDU
sent 3 b'07B93F5F'
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000019800000040000000000000004303742393346363000' (25 bytes)
DEBUG:smpp.Client.2560105653648:Read submit_sm_resp PDU
sent 4 b'07B93F60'
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:Socket timeout, listening again
DEBUG:smpp.Client.2560105653648:Sending enquire_link PDU
DEBUG:smpp.Client.2560105653648:>>b'00000010000000150000000000000005' (16 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000010800000150000000000000005' (16 bytes)
DEBUG:smpp.Client.2560105653648:Read enquire_link_resp PDU
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:Socket timeout, listening again
DEBUG:smpp.Client.2560105653648:Sending enquire_link PDU
DEBUG:smpp.Client.2560105653648:>>b'00000010000000150000000000000006' (16 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000010800000150000000000000006' (16 bytes)
DEBUG:smpp.Client.2560105653648:Read enquire_link_resp PDU
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:Socket timeout, listening again
DEBUG:smpp.Client.2560105653648:Sending enquire_link PDU
DEBUG:smpp.Client.2560105653648:>>b'00000010000000150000000000000007' (16 bytes)
DEBUG:smpp.Client.2560105653648:Waiting for PDU...
DEBUG:smpp.Client.2560105653648:<<b'00000010800000150000000000000007' (16 bytes)
DEBUG:smpp.Client.2560105653648:Read enquire_link_resp PDU
DEBUG:smpp.Client.2560105653648:Waiting for PDU...

**Comment by eigenein** [comment]
There is no any particular error in your log, I would rather address this question to your SMPP provider

**Comment by sairmali** [comment]
i will ask to my provider please wait for my response
