### ISSUE TITLE
How to Solve Invalid Message Validity Period (Expiry Time)?

### ISSUE THREAD

**Issue by lujamaharjan** [python-smpplib/python-smpplib#254]
I have a dedicated server set up solely for receiving SMS. It works with two telecom providers, but with one of them, I'm encountering an error: "Invalid message validity period". can I have any validity time configurations in smpplib. 

```
import smpplib.gsm
import smpplib.client
import smpplib.consts

from decouple import config
from callback.callaback import sms_received_function

client = smpplib.client.Client(config('NCELL_SMSC_IP_KTM'), config('NCELL_SMSC_PORT_KTM'), timeout=10)
client.set_message_received_handler(lambda pdu: sms_received_function(pdu))
client.connect()

client.bind_receiver(system_id = 'SystemID', password = config('NCELL_SYSTEM_PASSWORD_KTM'))
print("Listnening Ncell SMS ....")
client.listen()

```

**Comment by eigenein** [comment]
Hi Sachin,

Sorry for the slow response.

I'm not quite sure, at which point are you getting the error? As far as I know, the validity period can be set either on SMSc side or when sending a message via `submit_sm`

**Comment by lujamaharjan** [comment]
Thank you, @eigenein , for the clarification. I believe the issue lies on the telecom provider's side. I’ve confirmed this. I can successfully bind using the short code (e.g., SMS_Alert) with the associated username and password. However, the problem occurs when attempting to bind with the phone number (31040).
