### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by eigenein** [python-smpplib/python-smpplib#45]
Hi Kostya,

Could you consider publishing the package on PyPI? So far I can only find https://pypi.python.org/pypi/python3-smpplib/1.0.21 which is a fork and missing the latest changes.

**Comment by egorsmkv** [comment]
You can install this package using the "git+...." notation in a requirements file

**Comment by eigenein** [comment]
True, but it doesn't work well with `pip freeze`.

**Comment by azmeuk** [comment]
A pip package would be great!

**Comment by eigenein** [comment]
We're trying to claim `smpplib` name on PyPI, this will take some time. Stay tuned.

**Comment by eigenein** [comment]
@takinbo Hi Tim! I've been trying to reach you out via email and Twitter already to no avail. We'd like to publish our package on PyPI under the name of `smpplib` which is now under your name and looks abandoned. Could you be so kind to free up the name / transfer ownership to us please?

**Comment by Wahib13** [comment]
honestly, if we haven't heard from him I think we should find another name and publish it either way. this package is really useful and I think it should be made easily accessible. maybe `pysmpp`?

**Comment by eigenein** [comment]
We've already got a response, hoping to get the name quite soon.

**Comment by Wahib13** [comment]
oh okay that's great

**Comment by eigenein** [comment]
Agreement is not reached, created an issue with @pypa: https://github.com/pypa/warehouse/issues/5122

**Comment by eigenein** [comment]
Done! https://pypi.org/project/smpplib/

**Comment by geeksambhu** [comment]
Hi @eigenein, The PyPi homepage for `smpplib` refers to the forked version. Please update it 
https://pypi.org/project/smpplib/

**Comment by eigenein** [comment]
Hi @geeksambhu,

Thanks for pointing out, will be fixed with the next release!
