### ISSUE TITLE
'str' with 'max' validate error

### ISSUE THREAD

**Issue by AndreiSobolev** [python-smpplib/python-smpplib#67]
https://github.com/podshumok/python-smpplib/blob/c171237bd2eb9af337547aa2497f5a6aa9b84288/smpplib/command.py#L220

when i use parameter 'receipted_message_id' - i have this error:

    value = struct.pack(">HH", field_code, field_length) + fvalue
TypeError: can't concat str to bytes

**Comment by eigenein** [comment]
Hiya Andrei,

Thanks for reporting this. A couple of questions: which Python are you using (2 or 3) and which command are you sending (may be useful for reproducing)?

**Comment by AndreiSobolev** [comment]
Hello! 
I use python version 3.6, pdu -  "deliver_sm", param with error - "receipted_message_id".I tried transfer it as string and as byte
