### ISSUE TITLE
Problem with some symbols @ _ $

### ISSUE THREAD

**Issue by SohanChy** [python-smpplib/python-smpplib#79]
I am using the latest(master) version of the library.
Mainly sending English & Bengali sms.

Everything is working fine, even complex Bengali symbols are being nicely sent but specific symbols are not being sent correctly.
Three known symbols: 
`@ _ $`
These symbols are sent as `¿`.

Code attached:

```python
    parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(messageBody)
    pdus = ""

    try:
        for part in parts:
            pdu = client.send_message(
                source_addr_ton=smpplib.consts.SMPP_TON_INTL,
                # source_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
                # Make sure it is a byte string, not unicode:
                source_addr=sender,

                dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
                # dest_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
                # Make sure thease two params are byte strings, not unicode:
                destination_addr=reciever,
                short_message=part,

                data_coding=encoding_flag,
                esm_class=msg_type_flag,
                registered_delivery=True,
            )
            pdus = pdus + " " + str(pdu.sequence) + ","
... ...
```

**Comment by eigenein** [comment]
Hello Sohan,

This happened to me when SMSc default encoding table didn't match the table that we have. Use of `SMPP_ENCODING_DEFAULT` is actually discouraged by the specs.

What if you try either of the following encodings?

```python
parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(message_body, encoding=consts.SMPP_ENCODING_ISO88591)
```

```python
parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(message_body, encoding=consts. SMPP_ENCODING_ISO10646)
```

**Comment by eigenein** [comment]
Hi @SohanChy,

Did you have a chance to test the suggestion?

**Comment by SohanChy** [comment]
Hi @eigenein Thanks for your suggestion and prompt response. 
Sorry, I was busy with some other things due to which I could not test the suggestion yet.
Hopefully I will test it within this week & get back to you.

**Comment by eigenein** [comment]
Please reopen the issue if it's still actual
