### ISSUE TITLE
Constant value not correct

### ISSUE THREAD

**Issue by brekko** [python-smpplib/python-smpplib#81]
In the file consts.py there is a constant at line 206
SMPP_UDHIEIE_PORT16 = 0x04

the correct value is 0x05, can someone please fix it?

Thank you.

**Comment by eigenein** [comment]
Hi @brekko,

Thanks for reporting that, we'll make the change.

Note for myself:

```python
SMPP_UDHIEIE_PORT16 = 0x05
SMPP_UDHIEIE_CONCATENATED16 = 0x08
```
