### ISSUE TITLE
Support for Multiple Recipients

### ISSUE THREAD

**Issue by borsn** [python-smpplib/python-smpplib#96]
SMPP supports multiple recipients.

Does smpplib support it?

And how do I implement it?

**Comment by eigenein** [comment]
Duplicate of https://github.com/python-smpplib/python-smpplib/issues/80

**Comment by Lynesth** [comment]
@borsn I would just like to add that even though it is supported by SMPP, there's like no SMPP provider actually supporting the `SUBMIT_MULTI` operation. If you found one, I am interested (and will add the feature to python-smpplib).
